services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@database.local:5432/bonusx_db
      - S3_ENDPOINT=http://storage.local:9000
      - S3_BUCKET_NAME=bonusx-bucket
      - AWS_REGION=eu-west-1
      - PORT=80
    env_file:
      - .env
    ports:
      - '8080:80'
    depends_on:
      - postgres
      - s3ninja
    networks:
      - bonusx-network
    restart: unless-stopped

  postgres:
    hostname: database.local
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bonusx_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bonusx-network
    restart: unless-stopped

  s3ninja:
    hostname: storage.local
    image: scireum/s3-ninja:latest
    expose:
      - '9000'
    ports:
      - '9000:9000'
    volumes:
      - s3ninja_data:/home/sirius/data
    networks:
      - bonusx-network
    restart: unless-stopped

volumes:
  postgres_data:
  s3ninja_data:

networks:
  bonusx-network:
    driver: bridge
