services:
  backend:
    build:
      context: ..
      dockerfile: ./backend/dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@database.local:5432/bonusx_db
      - S3_ENDPOINT=http://host.docker.internal:9000 # to be reachable from the host machine
      - S3_BUCKET_NAME=bonusx-bucket
      - S3_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - S3_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_REGION=eu-west-1
      - PORT=8080
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - s3ninja
    networks:
      - bonusx-network
    restart: unless-stopped

  postgres:
    hostname: database.local
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bonusx_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bonusx-network
    restart: unless-stopped

  s3ninja:
    hostname: storage.local
    image: scireum/s3-ninja:latest
    environment:
      - AWS_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - 9000:9000
    volumes:
      - s3ninja_data:/home/sirius/data
    networks:
      - bonusx-network
    restart: unless-stopped

volumes:
  postgres_data:
  s3ninja_data:

networks:
  bonusx-network:
    driver: bridge
